spring:
  mvc:
    async:
      request-timeout: 0
  task:
    execution:
      pool:
        core-size: 8
        max-size: 50
        queue-capacity: 100
        keep-alive: 60s
  datasource:
    url: jdbc:h2:file:./data/textdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  ai:
    mcp:
      server:
        name: text-content-server
        version: 0.0.1
        type: ASYNC
        stdio: false
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        sse-message-endpoint: /mcp/message
        sse-reconnect-interval: 5000
        sse-heartbeat-interval: 30000

server:
  port: 8080
  servlet:
    encoding:
      force: true
    session:
      timeout: 60m
  connection-timeout: 0
  tomcat:
    connection-timeout: 0
    keep-alive-timeout: 0
    max-http-form-post-size: 2MB
    max-swallow-size: 2MB
    max-http-header-size: 8KB
    max-keep-alive-requests: -1
    max-connections: 10000
    threads:
      max: 200

logging:
  level:
    Exposed: DEBUG
    org.springframework.web: DEBUG
    org.springframework: INFO
    com.example: DEBUG
  file:
    name: ./target/starter-webmvc-server.log 